# -*- coding: utf-8 -*-
"""PROYECTO BIG DATA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_5-eEpaaVWobhOkX_HgWMvqyM0e7XNk6
"""

!pip install pyspark
!pip install reportlab -q

import pandas as pd
import matplotlib.pyplot as plt

from pyspark.sql import SparkSession
from pyspark.sql.functions import *
from pyspark.sql.functions import trim
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import cm
from reportlab.platypus import Image
import os

spark = SparkSession.builder \
    .appName("ProyectoBigDataTurismo") \
    .config("spark.sql.ansi.enabled", "false") \
    .getOrCreate()

from google.colab import files

uploaded = files.upload()

df = spark.read.csv(
    "hospedajes.csv",
    header=True,
    inferSchema=True
)

for c in df.columns:
    df = df.withColumn(c, trim(col(c).cast("string")))

df = df.withColumn("HABITACIONES", col("HABITACIONES").cast("int"))
df = df.withColumn("CAMAS", col("CAMAS").cast("int"))

df.printSchema()

df.show(10)

print("="*60)
print("REPORTE 1: TOTAL DE ESTABLECIMIENTOS")
print("="*60)

total = df.count()

print(f"Total de establecimientos registrados: {total}")

# Cantidad antes de eliminar duplicados
antes = df.count()

# Eliminar registros duplicados
df = df.dropDuplicates()

# Cantidad después de eliminar duplicados
despues = df.count()

print(f"Duplicados eliminados: {antes - despues}")
print(f"Total de registros después de la limpieza: {despues}")

df = df.dropDuplicates()

from pyspark.sql.functions import col,isnan,when,count

df.select([
    count(
        when(col(c).isNull(),c)
    ).alias(c)
    for c in df.columns
]).show()

df = df.na.fill({
    "WEB":"No registra",
    "CORREO_ELECTRONICO":"No registra",
    "TELEFONO":"No registra",
    "REPRESENTANTE_LEGAL":"No registra"
})

df = df.withColumn(
    "HABITACIONES",
    col("HABITACIONES").cast("int")
)

df = df.withColumn(
    "CAMAS",
    col("CAMAS").cast("int")
)

df = df.withColumn(
    "CAMAS_POR_HABITACION_CALCULADA",
    round(try_divide(col("CAMAS"), col("HABITACIONES")), 2)
)

df.write.mode("overwrite").parquet("turismo_limpio")

"""**REPORTES**"""

print(df.count()) #TOTAL DE ESTABLECIMIENTOS

print("="*60)
print("REPORTE 2: ESTABLECIMIENTOS POR PROVINCIA")
print("="*60)

provincia = (
    df.groupBy("PROVINCIA")
      .count()
      .orderBy(desc("count"))
)

provincia.show()

prov = provincia.toPandas()

display(prov)

plt.figure(figsize=(12,6))
plt.bar(prov["PROVINCIA"], prov["count"])
plt.xticks(rotation=90)
plt.xlabel("Provincia")
plt.ylabel("Cantidad")
plt.title("Cantidad de establecimientos por provincia")
plt.grid(axis="y")

plt.savefig("grafico_provincias.png", dpi=300, bbox_inches="tight")

plt.show()

print("="*60)
print("REPORTE 3: HABITACIONES POR PROVINCIA")
print("="*60)

habitaciones = (
    df.groupBy("PROVINCIA")
      .agg(sum("HABITACIONES").alias("TOTAL_HABITACIONES"))
      .orderBy(desc("TOTAL_HABITACIONES"))
)

habitaciones.show()

habitaciones_pd = habitaciones.toPandas()

display(habitaciones_pd)

plt.figure(figsize=(12,6))
plt.bar(habitaciones_pd["PROVINCIA"], habitaciones_pd["TOTAL_HABITACIONES"])
plt.xticks(rotation=90)
plt.title("Habitaciones por provincia")
plt.savefig("grafico_habitaciones.png", dpi=300, bbox_inches="tight")
plt.show() # HABITACIONES POR PROVINCIA

print("="*60)
print("REPORTE 4: CAMAS POR PROVINCIA")
print("="*60)

camas = (
    df.groupBy("PROVINCIA")
      .agg(sum("CAMAS").alias("TOTAL_CAMAS"))
      .orderBy(desc("TOTAL_CAMAS"))
)

camas.show()

camas_pd = camas.toPandas()

display(camas_pd)

plt.figure(figsize=(12,6))
plt.bar(camas_pd["PROVINCIA"], camas_pd["TOTAL_CAMAS"])
plt.xticks(rotation=90)
plt.title("Camas por provincia")

plt.savefig("grafico_camas.png", dpi=300, bbox_inches="tight")

plt.show()

print("="*60)
print("REPORTE 5: CATEGORÍAS")
print("="*60)

categoria = (
    df.groupBy("CATEGORIA")
      .count()
      .orderBy(desc("count"))
)

categoria.show()

categoria_pd = categoria.toPandas()

display(categoria_pd)

plt.figure(figsize=(8,8))
plt.pie(
    categoria_pd["count"],
    labels=categoria_pd["CATEGORIA"],
    autopct="%1.1f%%"
)

plt.title("Distribución por categoría")

plt.savefig("grafico_categorias.png", dpi=300, bbox_inches="tight")

plt.show()

print("="*60)
print("REPORTE 6: CLASE")
print("="*60)

clase = (
    df.groupBy("CLASE")
      .count()
      .orderBy(desc("count"))
)

clase.show()

clase_pd = clase.toPandas()

display(clase_pd) #CLASE
plt.figure(figsize=(10,5))
plt.bar(clase_pd["CLASE"], clase_pd["count"])
plt.title("Cantidad de establecimientos por clase")
plt.xlabel("Clase")
plt.ylabel("Cantidad")
plt.grid(axis="y")

plt.savefig("grafico_clase.png", dpi=300, bbox_inches="tight")

plt.show()

print("="*60)
print("REPORTE 7: TOP 10 ESTABLECIMIENTOS")
print("="*60)

top = (
    df.orderBy(desc("HABITACIONES"))
)

top.show(10)

display(top.limit(10).toPandas()) #TOP ESTABLECIMIENTOS

print("="*60)
print("REPORTE 8: TOP 10 POR CAMAS")
print("="*60)

top = (
    df.orderBy(desc("CAMAS"))
)

top.show(10)

display(top.limit(10).toPandas()) # TOP CAMAS

print("="*60)
print("REPORTE 9: PROMEDIO DE HABITACIONES")
print("="*60)

prom = df.select(
    round(avg("HABITACIONES"),2).alias("Promedio")
)

prom.show()

display(prom.toPandas()) #PROMEDIO DE HABITACIONES

print("="*60)
print("REPORTE 10: PROMEDIO DE CAMAS")
print("="*60)

prom = df.select(
    round(avg("CAMAS"),2).alias("Promedio")
)

prom.show()

display(prom.toPandas()) #PROMEDIO DE CAMAS

distritos = df.groupBy("DISTRITO") \
              .count() \
              .orderBy(desc("count")) #DISTRITOS CON MÁS HOTELES
distritos_pd = distritos.toPandas()

display(distritos_pd)

plt.figure(figsize=(15,6))
plt.bar(distritos_pd["DISTRITO"], distritos_pd["count"])
plt.xticks(rotation=90)
plt.title("Cantidad de hospedajes por distrito")
plt.xlabel("Distrito")
plt.ylabel("Cantidad")
plt.grid(axis="y")

plt.savefig("grafico_distritos.png", dpi=300, bbox_inches="tight")

plt.show()

df = df.withColumn(
    "TIENE_WEB",
    when(col("WEB").isNull(),"NO")
    .otherwise("SI")
)

df.groupBy("TIENE_WEB").count().show() # Establecimientos con página web

print("="*60)
print("REPORTE 13: PROVINCIA VS CATEGORÍA")
print("="*60)

tabla = (
    df.groupBy("PROVINCIA", "CATEGORIA")
      .count()
      .orderBy("PROVINCIA", "CATEGORIA")
)

tabla.show()

tabla_pd = tabla.toPandas()

display(tabla_pd)

pivot = tabla_pd.pivot(
    index="PROVINCIA",
    columns="CATEGORIA",
    values="count"
).fillna(0)

pivot.plot(
    kind="bar",
    figsize=(14,6)
)

plt.title("Provincia vs Categoría")
plt.xlabel("Provincia")
plt.ylabel("Cantidad")
plt.xticks(rotation=90)
plt.grid(axis="y")

plt.savefig("grafico_provincia_categoria.png", dpi=300, bbox_inches="tight")

plt.show()